services:
  mysql:
    image: mysql:8.4.5
    container_name: readmate-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: readmate
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - dev-network

volumes:
  mysql_data:
    driver: local

networks:
  dev-network:
    driver: bridge